name: 'Install Dependencies'
description: 'Installs all dependencies needed for testing'
author: 'AlCalzone'
inputs:
  node-version:
    description: 'Node.js version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --immutable
