# Offer the fix lint bot command
offerLintFix:
  # Which job name to look for
  jobName: lint
  # Define which linter outputs should be checked for auto-fixability
  linters:
    - eslint
    - wotan
    - prettier

# Check whether the resulting squash-commit will be semantic
semanticSquash: true

# Configure closing stale issues
stale:
  # Which job name triggers the stale action
  jobName: stale
  actions:
    - action: close
      afterDays: 3 # How long issues with these labels may stay open
      labels: # Which labels mark an issue as closeable
        - 'cannot fix ❌'
        - 'duplicate'
        - 'external'
        - 'wontfix'
        - 'working as intended ✔'
        - 'stale 💤'
      # What to comment when an issue gets closed
      comment: |
        This issue has not seen any recent activity and was marked as "${label}".
        Closing for housekeeping purposes... 🧹

        Feel free to reopen if the issue persists.

    # Wait 7 days for info, then mark as stale
    - action: label
      afterDays: 7
      labels:
        - 'waiting for info ⏳'
      label: 'stale 💤'

    # Only wait 2 days for people who don't fill out issue templates
    - action: label
      afterDays: 2
      labels:
        - 'incomplete ⚠'
      label: 'stale 💤'
      comment: |
        Sorry, we cannot act on issues where the issue template is not filled out completely 😕.
        Please fill out the entire template or the issue will be closed soon.

# Configure auto-labeling
autoLabel:
  # Add one array entry for each rule
  - pattern: 'packages\/config\/config\/(.*\/)?.+\.json|\.gitignore' # Regex to match filenames
    only: true # Whether non-matching files should be allowed
    remove: false # Whether to remove the label if the rule no longer applies
    label: 'config ⚙' # Which label to add/remove

# Whitelist which workflows from forks may be auto-approved:
approveWorkflow:
  # Auto-approve only workflows for config file changes
  files: 'packages/config/config/**/*.json' # May also be an array of strings
