# Offer the fix lint bot command
offerLintFix:
  # Which job name to look for
  jobName: lint
  # Define which linter outputs should be checked for auto-fixability
  linters:
    - eslint
    - wotan
    - prettier

# Check whether the resulting squash-commit will be semantic
semanticSquash: true

# Configure closing stale issues
stale:
  # Which job name to look for
  jobName: stale
  # Which labels mark an issue as closeable
  labels:
    - 'cannot fix ❌'
    - 'duplicate'
    - 'external'
    - 'wontfix'
    - 'working as intended ✔'
  afterDays: 3
  comment: |
    This issue hasn't seen any recent activity and was marked as ${label}.
    Closing for housekeeping purposes... 🧹