# Commands to start on workspace startup
tasks:
  - init: |
      yarn config set enableGlobalCache false
      yarn config set cacheFolder .yarn/cache
      cat .yarnrc.yml
      yarn config get cacheFolder
      sleep 15
      yarn install
      yarn build
    # command: yarn watch # Start TypeScript compiler in watch mode

# Auto-install VSCode extensions
vscode:
  extensions:
    # - rebornix.project-snippets
    - dbaeumer.vscode-eslint
    - Orta.vscode-jest
    - esbenp.prettier-vscode
    - EditorConfig.EditorConfig
    - arcanis.vscode-zipfs

# Configure prebuilds
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
