# Commands to start on workspace startup
tasks:
  - init: |
      yarn install
      yarn build
    command: |
      bash .gitpod/setup-git.sh
      gp sync-done prepare

  - name: Print help
    openMode: split-right
    command: bash .gitpod/help.sh

# Auto-install VSCode extensions
vscode:
  extensions:
    # - rebornix.project-snippets # disabled because not available
    # - Orta.vscode-jest          # disabled because it is annoying on gitpod
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - EditorConfig.EditorConfig
    - arcanis.vscode-zipfs

# Configure prebuilds
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
