# Commands to start on workspace startup
env:
  # Avoids cross-link issues due to different filesystems between /home and /workspaces
  YARN_GLOBAL_FOLDER: '.yarn/global'
  YARN_CACHE_FOLDER: '.yarn/cache'
  YARN_ENABLE_GLOBAL_CACHE: 'false'
  # Avoids interactive prompt causing container creation to hang
  COREPACK_ENABLE_DOWNLOAD_PROMPT: '0'

tasks:
  - init: |
      corepack enable
      yarn
      yarn bootstrap
    command: |
      bash .gitpod/setup-git.sh
      gp sync-done prepare

  - name: Print help
    openMode: split-right
    command: bash .gitpod/help.sh

# Auto-install VSCode extensions
vscode:
  extensions:
    - dprint.dprint
    - dbaeumer.vscode-eslint
    - EditorConfig.EditorConfig
    - zwave-js.config-editor

# Configure prebuilds
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
