enableGlobalCache: true

# Only necessary to test TypeScript beta
nodeLinker: 'node-modules'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.0.0-rc.6.cjs
