compressionLevel: mixed

enableGlobalCache: true

nodeLinker: pnpm

plugins:
  - checksum: e09b9d94c3e4f271d75c0aa5364f424f9d654a086b7f6c8a16c7dd46ee6b0face259054cb4ac916080a1ec49a6519e04858b3f340fd3a9f325b6b344c34839c6
    path: .yarn/plugins/@yarnpkg/plugin-changed.cjs
    spec: "https://raw.githubusercontent.com/zwave-js/yarn-plugins/master/packages/changed/bundles/%40yarnpkg/plugin-changed.js"

preferInteractive: true
