import { ZWaveNode } from "../..";
import { IDriver } from "../driver/IDriver";

export abstract class CCAPI {
	public constructor(
		protected readonly driver: IDriver,
		protected readonly node: ZWaveNode,
	) {}
}

// This interface is auto-generated by maintenance/generateCCAPIInterface.ts
// Do not edit it by hand or your changes will be lost
export interface CCAPIs {
	Basic: import("./BasicCC").BasicCCAPI;
	Battery: import("./BatteryCC").BatteryCCAPI;
}
