name: 'Upload Build Cache'
description: 'Uploads build artifacts to be used in later jobs'
author: 'AlCalzone'

runs:
  using: "composite"
  steps:
    - name: Compress build artifacts # Uploading or downloading many files takes ages
      shell: bash
      run: tar -cvzf built.tgz packages/*/build packages/*/src packages/*/*.tsbuildinfo

    - name: Upload build artifacts to cache
      uses: actions/upload-artifact@v3
      with:
        name: built
        path: built.tgz
        retention-days: 1 # We don't need this any longer than the workflow takes, but 1 day is the minimum
