name: 'Update typed documentation'
description: 'Creates or updates a PR with a documentation update'
author: 'AlCalzone'
inputs:
  githubToken:
    description: 'The github token to use for authentication'
    required: true
runs:
  using: 'node16'
  main: 'main.js'
