name: 'Automatically approve workflow runs'

on:
  workflow_dispatch: {}
  schedule:
    # every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  approve-workflows:
    if: github.repository == 'zwave-js/node-zwave-js' # Don't run in forks
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        shell: bash
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check and approve workflows
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          script: |
            const bot = require(`${process.env.GITHUB_WORKSPACE}/.github/bot-scripts/index.js`);
            const workflows = [
              ".github/workflows/generate-docs.yml",
              ".github/workflows/test-and-release.yml",
              ".github/workflows/codeql-analysis.yml"
            ];
            const whitelist = [
              "packages/config/config/**/*.json"
            ];
            return bot.approveWorkflows({github, context, workflows, whitelist});
