/*!
 * This script generates the exports for all utility types from `src/lib/commandclass/*CC.ts`
 */

import * as fs from "fs-extra";
import * as path from "path";
import ts from "typescript";
import {
	compareStrings,
	formatWithPrettier,
	loadTSConfig,
	projectRoot,
} from "./shared";

// Define where the CC index file is located
const ccIndexFile = path.join(projectRoot, "src/lib/commandclass/index.ts");

function findExports() {
	// Create a Program to represent the project, then pull out the
	// source file to parse its AST.

	const tsConfig = loadTSConfig();
	const program = ts.createProgram(tsConfig.fileNames, tsConfig.options);

	// Used to remember the exports we found
	const ccExports = new Map<string, { name: string; typeOnly: boolean }[]>();
	function addExport(
		filename: string,
		name: string,
		typeOnly: boolean,
	): void {
		if (!ccExports.has(filename)) ccExports.set(filename, []);
		ccExports.get(filename)!.push({ name, typeOnly });
	}

	// Scan all source files
	for (const sourceFile of program.getSourceFiles()) {
		const relativePath = path
			.relative(projectRoot, sourceFile.fileName)
			.replace(/\\/g, "/");

		// Only look at files in this package
		if (relativePath.startsWith("..")) continue;

		// Only look at the commandclass dir
		if (!relativePath.includes("/commandclass/")) {
			continue;
		}
		// Ignore test files and the index
		if (
			relativePath.endsWith(".test.ts") ||
			relativePath.endsWith("index.ts")
		) {
			continue;
		}
		const fileFullText = sourceFile.getFullText();

		// Visit each root node to see if it has a `@apiExport` comment
		ts.forEachChild(sourceFile, (node) => {
			// Define which declaration types we need to export
			if (
				ts.isEnumDeclaration(node) ||
				ts.isTypeAliasDeclaration(node) ||
				ts.isInterfaceDeclaration(node)
			) {
				const leadingComments = ts.getLeadingCommentRanges(
					fileFullText,
					node.pos,
				);
				if (!leadingComments) return;

				for (const comment of leadingComments) {
					const commentText = fileFullText.slice(
						comment.pos,
						comment.end,
					);
					if (commentText.includes("@publicAPI")) {
						// It has, make sure we're trying to access a node that is actually exported
						if (
							!node.modifiers?.some(
								(m) => m.kind === ts.SyntaxKind.ExportKeyword,
							)
						) {
							const location = ts.getLineAndCharacterOfPosition(
								sourceFile,
								node.getStart(sourceFile, false),
							);
							throw new Error(
								`${relativePath}:${location.line} Found @publicAPI comment, but the node ${node.name.text} is not exported!`,
							);
						}
						addExport(
							sourceFile.fileName,
							node.name.text,
							ts.isTypeAliasDeclaration(node) ||
								ts.isInterfaceDeclaration(node),
						);
					}
				}
			}
		});
	}
	return ccExports;
}

export async function generateCCExports(): Promise<void> {
	let fileContent = `
// This file is auto-generated by maintenance/generateCCExports.ts
// Do not edit it by hand or your changes will be lost!

import * as fs from "fs";

// Load all CC files to ensure all metadata gets loaded
const definedCCs = fs
	.readdirSync(__dirname)
	.filter((file) => /CC\.(js|ts)$/.test(file));
for (const file of definedCCs) {
	require(\`./\${file}\`);
}

// explicitly export specific things from the CCs
`;

	// Generate type and value exports for all found symbols
	for (const [filename, fileExports] of [
		...findExports().entries(),
	].sort(([fileA], [fileB]) => compareStrings(fileA, fileB))) {
		const relativePath = path
			.relative(ccIndexFile, filename)
			// normalize to slashes
			.replace(/\\/g, "/")
			// TS imports may not end with ".ts"
			.replace(/\.ts$/, "")
			// By passing the index file as "from", we get an erraneous "../" at the path start
			.replace(/^\.\.\//, "./");
		const typeExports = fileExports.filter((e) => e.typeOnly);
		if (typeExports.length) {
			fileContent += `export type { ${typeExports
				.map((e) => e.name)
				.join(", ")} } from "${relativePath}"\n`;
		}
		const valueExports = fileExports.filter((e) => !e.typeOnly);
		if (valueExports.length) {
			fileContent += `export { ${valueExports
				.map((e) => e.name)
				.join(", ")} } from "${relativePath}"\n`;
		}
	}

	// And write the file
	await fs.writeFile(
		ccIndexFile,
		formatWithPrettier(ccIndexFile, fileContent),
		"utf8",
	);
}

if (!module.parent) void generateCCExports();
