// This file is auto-generated by maintenance/generateCCExports.ts
// Do not edit it by hand or your changes will be lost!

import * as fs from "fs";

// Load all CC files to ensure all metadata gets loaded
const definedCCs = fs
	.readdirSync(__dirname)
	.filter((file) => /CC.(js|ts)$/.test(file));
for (const file of definedCCs) {
	require(`./${file}`);
}

// explicitly export specific things from the CCs
export { AlarmSensorType } from "./AlarmSensorCC";
export type { AssociationGroup } from "./AssociationGroupInfoCC";
export { AssociationGroupInfoProfile } from "./AssociationGroupInfoCC";
export { BatteryChargingStatus, BatteryReplacementStatus } from "./BatteryCC";
export { BinarySensorType } from "./BinarySensorCC";
export { CentralSceneKeys } from "./CentralSceneCC";
export { ScheduleOverrideType } from "./ClimateControlScheduleCC";
export { Weekday } from "./ClockCC";
export type { ColorTable } from "./ColorSwitchCC";
export { ColorComponent } from "./ColorSwitchCC";
export type { ConfigValue } from "./ConfigurationCC";
export type { DoorHandleStatus } from "./DoorLockCC";
export { DoorLockMode, DoorLockOperationType } from "./DoorLockCC";
export {
	FirmwareUpdateRequestStatus,
	FirmwareUpdateStatus,
	FirmwareUpdateActivationStatus,
	FirmwareDownloadStatus,
} from "./FirmwareUpdateMetaDataCC";
export { DeviceIdType } from "./ManufacturerSpecificCC";
export { RateType } from "./MeterCC";
export type { Association } from "./MultiChannelAssociationCC";
export type { MultilevelSensorValue } from "./MultilevelSensorCC";
export { LevelChangeDirection, SwitchType } from "./MultilevelSwitchCC";
export { LocalProtectionState, RFProtectionState } from "./ProtectionCC";
export { ThermostatMode } from "./ThermostatModeCC";
export { ThermostatOperatingState } from "./ThermostatOperatingStateCC";
export { SetbackType } from "./ThermostatSetbackCC";
export { ThermostatSetpointType } from "./ThermostatSetpointCC";
export { ZWavePlusRoleType, ZWavePlusNodeType } from "./ZWavePlusCC";
