name: Check public API surface

# Run this workflow on all pull requests
on:
  pull_request: {}

jobs:
  # This job checks if a PR changes the public API surface
  check-and-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # This should be LTS

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --immutable

    - name: Compile TypeScript code
      run: yarn run build

    - name: Generate API report
      run: yarn run extract-api

    - name: Comment on PR
      if: failure()
      run: |
        echo "The public API surface has changed!" >> $GITHUB_STEP_SUMMARY
        echo "Please run `yarn extract-api --local` and review the changes, then commit them if desired." >> $GITHUB_STEP_SUMMARY
